# Generated by Django 5.0.1 on 2024-03-14 10:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان دسته بندی')),
                ('slug', models.SlugField(max_length=500, verbose_name='ادرس دسته بندی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات ')),
                ('status', models.BooleanField(default=True, verbose_name='ایا نشان داده شود؟')),
                ('position', models.IntegerField(verbose_name='موقعیت نمایش')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
                'ordering': ('-position',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان خبر')),
                ('slug', models.SlugField(max_length=500, unique_for_date='publish')),
                ('body', models.TextField(blank=True, null=True, verbose_name='متن خبر')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'پیش نویس'), ('published', 'منتشر شده')], default='draft', max_length=15, verbose_name='وضعیت')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('Category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='news.category')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'خبرها',
                'ordering': ('-publish',),
            },
        ),
    ]
